**Importing** **Libraries**

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
tf.__version__

'2.3.0'

**Data** **Preprocessing**

In [3]:
from google.colab import files 
uploaded = files.upload() 


Saving Churn_Modelling.csv to Churn_Modelling.csv


In [4]:
import io 
dataset = pd.read_csv(io.BytesIO(uploaded['Churn_Modelling.csv'])) 


In [5]:
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [6]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [7]:
print(y)

[1 0 1 ... 1 1 0]


**Encoding Categorical Data**

Label Encoding the "General" column

In [8]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


**One Hot Encoding the "Geography" column**

In [9]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


**Splitting the dataset into the Training set and Test set**

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

**Feature Scaling**

In [12]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

**Part 2 - Building the ANN**

In [13]:
# Initializing the ANN
ann = tf.keras.models.Sequential()

In [14]:
# Adding the input layer and the first hidden layer
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [15]:
# Adding the second hidden layer
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [16]:
# Adding the output layer
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

**Part 3 - Training the ANN**

In [17]:
# Compiling the ANN
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [20]:
# Training the ANN on the Training set
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 0s 947us/step - loss: 0.3333 - accuracy: 0.8644
Epoch 2/100
250/250 [==============================] - 0s 889us/step - loss: 0.3329 - accuracy: 0.8655
Epoch 3/100
250/250 [==============================] - 0s 866us/step - loss: 0.3332 - accuracy: 0.8636
Epoch 4/100
250/250 [==============================] - 0s 865us/step - loss: 0.3327 - accuracy: 0.8651
Epoch 5/100
250/250 [==============================] - 0s 895us/step - loss: 0.3330 - accuracy: 0.8636
Epoch 6/100
250/250 [==============================] - 0s 877us/step - loss: 0.3328 - accuracy: 0.8650
Epoch 7/100
250/250 [==============================] - 0s 843us/step - loss: 0.3328 - accuracy: 0.8637
Epoch 8/100
250/250 [==============================] - 0s 862us/step - loss: 0.3329 - accuracy: 0.8639
Epoch 9/100
250/250 [==============================] - 0s 828us/step - loss: 0.3328 - accuracy: 0.8645
Epoch 10/100
250/250 [==============================] - 0s 884us/step - l

## **Part 4 - Making the predictions and evaluating the model**

In [22]:
# Predicting the Test set results
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [23]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1519   76]
 [ 193  212]]


0.8655